package com.project.jingmaoquan.mapper;

import com.project.jingmaoquan.model.Second;
import com.project.jingmaoquan.model.SecondExample;
import com.project.jingmaoquan.model.SecondWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SecondMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    long countByExample(SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int deleteByExample(SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int deleteByPrimaryKey(Long secondId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int insert(SecondWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int insertSelective(SecondWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    List<SecondWithBLOBs> selectByExampleWithBLOBsWithRowbounds(SecondExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    List<SecondWithBLOBs> selectByExampleWithBLOBs(SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    List<Second> selectByExampleWithRowbounds(SecondExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    List<Second> selectByExample(SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    SecondWithBLOBs selectByPrimaryKey(Long secondId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondWithBLOBs record, @Param("example") SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") SecondWithBLOBs record, @Param("example") SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int updateByExample(@Param("record") Second record, @Param("example") SecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int updateByPrimaryKeySelective(SecondWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SecondWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    int updateByPrimaryKey(Second record);
}