package com.project.jingmaoquan.model;

public class Second {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.second_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long secondId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.name
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.price
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.publisher_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.publish_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.state
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.view_count
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand.comment_count
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Integer commentCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.second_id
     *
     * @return the value of second_hand.second_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getSecondId() {
        return secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.second_id
     *
     * @param secondId the value for second_hand.second_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setSecondId(Long secondId) {
        this.secondId = secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.name
     *
     * @return the value of second_hand.name
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.name
     *
     * @param name the value for second_hand.name
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.price
     *
     * @return the value of second_hand.price
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.price
     *
     * @param price the value for second_hand.price
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.publisher_id
     *
     * @return the value of second_hand.publisher_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.publisher_id
     *
     * @param publisherId the value for second_hand.publisher_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.publish_time
     *
     * @return the value of second_hand.publish_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.publish_time
     *
     * @param publishTime the value for second_hand.publish_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.state
     *
     * @return the value of second_hand.state
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.state
     *
     * @param state the value for second_hand.state
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.view_count
     *
     * @return the value of second_hand.view_count
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.view_count
     *
     * @param viewCount the value for second_hand.view_count
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand.comment_count
     *
     * @return the value of second_hand.comment_count
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand.comment_count
     *
     * @param commentCount the value for second_hand.comment_count
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
}