package com.project.jingmaoquan.model;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_name
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.money
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.publisher_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.state
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.detail
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_name
     *
     * @return the value of task.task_name
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.money
     *
     * @return the value of task.money
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.money
     *
     * @param money the value for task.money
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.publisher_id
     *
     * @return the value of task.publisher_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.publisher_id
     *
     * @param publisherId the value for task.publisher_id
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.state
     *
     * @return the value of task.state
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.state
     *
     * @param state the value for task.state
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_time
     *
     * @return the value of task.update_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_time
     *
     * @param updateTime the value for task.update_time
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.detail
     *
     * @return the value of task.detail
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.detail
     *
     * @param detail the value for task.detail
     *
     * @mbg.generated Tue May 12 17:38:09 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}